-- 하루 메뉴별 총 매출

CREATE TABLE SUBMIT_ORDER (
	ORDERNUM INT NOT NULL AUTO_INCREMENT COMMENT '번호'
	,MENU            VARCHAR(20)     NOT NULL         COMMENT '카페 메뉴'
   	,ORDER_COUNT     INT            NOT NULL         COMMENT '총 주문 수량'
	,ORDER_PAY	 	 INT			NOT NULL 		COMMENT '총 주문 가격'
	,ORDER_DATE 	DATETIME		NOT NULL			COMMENT '날짜'
	,PRIMARY KEY(ORDERNUM)
) DEFAULT CHARSET=utf8mb4;

DESC SUBMIT_ORDER ;

-- CAFE_MENU_NUM 구분, 메뉴 판별
SELECT DISTINCT  M.CAFE_MENU
FROM MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '100';

-- CAFE_MENU_NUM 구분, 메뉴 별 대분류 판별
SELECT DISTINCT  M.CAFE_MENU_DAE
FROM MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '101';


-- CAFE_MENU_NUM 구분, 메뉴 별 총 수량
SELECT MAX(MEMBER_ORDER_COUNT)
FROM MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '101';

-- CAFE_MENU_NUM 구분, 메뉴 별 총 주문 가격
SELECT SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '101';


INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, MAX(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '100'
AND   M.CAFE_MENU  = '아메리카노';

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, MAX(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '101'
AND   M.CAFE_MENU  = '생강차';

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, MAX(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '102'
AND   M.CAFE_MENU  = '핫 초코';


SELECT * FROM submit_order;

-- 하루 총 매출 

SELECT SUM(ORDER_PAY) FROM SUBMIT_ORDER WHERE ORDER_DATE LIKE '%2023-02-03%';
