-- 1. 회원 추가
INSERT INTO MEMBERTBL (MEMBER_ID,MEMBER_PW,MEMBER_GR,MEMBER_NICKNAME,MEMBER_BIRTH,​
                      MEMBER_EMAIL,MEMBER_JOINDATE,MEMBER_BLACKY,MEMBER_EVENTQTY)​
VALUES ('testUser00','testUse0pas','N','nickexam00','19930315','test@test.co.kr',NOW(),'N',0);​


-- 2. 메뉴 추가
INSERT INTO MENUTBL(CAFE_MENU,CAFE_MENU_DAE,CAFE_MENU_NUM,CAFE_PRICE)VALUES ('아메리카노','커피','00100','5400');​
INSERT INTO MENUTBL(CAFE_MENU,CAFE_MENU_DAE,CAFE_MENU_NUM,CAFE_PRICE)VALUES ('생강차','티','00101','3500');​
INSERT INTO MENUTBL(CAFE_MENU,CAFE_MENU_DAE,CAFE_MENU_NUM,CAFE_PRICE)VALUES ('핫 초코','음료','00102','4700');

-- 3. 주문 하기 (카트에 주문을 메뉴별​ 하나씩 개수별로 ​담을 때마다​ 해당 쿼리 하나 실행.​)
INSERT INTO ORDERTBL(MEMBER_ID,MEMBER_MENU_NUM,MEMBER_ORDER_COUNT,MEMBER_ORDER_DATE)​
VALUES ( (SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')       -- 회원 아이디​
         ,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '101') ​          -- 메뉴 코드 
         ,'10' ,NOW() );​                                                        -- 주문 수량

INSERT INTO ORDERTBL(MEMBER_ID,MEMBER_MENU_NUM,MEMBER_ORDER_COUNT,MEMBER_ORDER_DATE)​
VALUES ( (SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')​
         ,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '100')​
         ,'5' ,NOW() );


-- 4. 회원 별 주문내역 쿼리
INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY)​
SELECT DISTINCT O.MEMBER_ID, MAX(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)​
FROM MENUTBL M, ORDERTBL O ​
WHERE O.MEMBER_ID = 'testUser00'​
AND M.CAFE_MENU = O.MEMBER_MENU_NUM;

-> 결제시 이 테이블 기준으로 ORDERNUM으로 번호표를 뽑고 ORDER_PAY로 금액을 결제함.​
SELECT MEMBER_ORDERNUM FROM SONNIM WHERE MEMBER_ID = 'testUser00';​ -- (1번 번호표)

SELECT MEMBER_ORDER_PAY FROM SONNIM WHERE MEMBER_ORDERNUM = (SELECT MEMBER_ORDERNUM ​
FROM SONNIM WHERE MEMBER_ID = 'testUser01'); -- (1번 번호표의 가격)

-- 5. 정산 테이블
INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)​
SELECT DISTINCT M.CAFE_MENU, MAX(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()​
FROM MENUTBL M, ORDERTBL O ​
WHERE M.CAFE_MENU_NUM = '100'​
AND M.CAFE_MENU = '아메리카노'​
AND O.MEMBER_MENU_NUM = '아메리카노';​

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)​
SELECT DISTINCT M.CAFE_MENU, MAX(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()​
FROM MENUTBL M, ORDERTBL O ​
WHERE M.CAFE_MENU_NUM = '101'​
AND M.CAFE_MENU = '생강차'​
AND O.MEMBER_MENU_NUM = '생강차';​

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)​
SELECT DISTINCT M.CAFE_MENU, MAX(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()​
FROM MENUTBL M, ORDERTBL O ​
WHERE M.CAFE_MENU_NUM = '102'​
AND M.CAFE_MENU = '핫 초코'​
AND O.MEMBER_MENU_NUM = '핫 초코';

-- 하루 총 매출 ​
SELECT SUM(ORDER_PAY) FROM SUBMIT_ORDER WHERE ORDER_DATE LIKE '%2023-02-03%';​



-- ---------------------------------------------------------------------------


-- 초기화 (손님 테이블, 주문 테이블)
-- 결제 완료 시 
truncate `sonnim`;
DELETE FROM ordertbl WHERE  MEMBER_ID = 'testUser00';


-- 재주문 시도
INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '100')
,'99'
,NOW()
);

--  손님 별 추가
INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY)
SELECT DISTINCT O.MEMBER_ID,  MAX(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser00'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

-- 초기화하였으므로 1번 손님 번호표
SELECT MEMBER_ORDERNUM FROM SONNIM WHERE MEMBER_ID = 'testUser00';

-- 1번 손님 결제할 금액
SELECT MEMBER_ORDER_PAY FROM SONNIM WHERE MEMBER_ORDERNUM = (SELECT MEMBER_ORDERNUM ​
FROM SONNIM WHERE MEMBER_ID = 'testUser00');

SELECT * FROM SUBMIT_ORDER SO ;


-- 아메리카노 재정산
INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, MAX(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '100'
AND   M.CAFE_MENU  = '아메리카노'
AND   O.MEMBER_MENU_NUM = '아메리카노';

SELECT * FROM SONNIM S ;

SELECT MEMBER_ORDERNUM FROM SONNIM WHERE MEMBER_ID = 'testUser00';

SELECT MEMBER_ORDER_PAY FROM SONNIM WHERE MEMBER_ORDERNUM = (SELECT MEMBER_ORDERNUM ​
FROM SONNIM WHERE MEMBER_ID = 'testUser00');


