-- 멤버 추가 
INSERT INTO MEMBERTBL (
	MEMBER_ID
	,MEMBER_PW
	,MEMBER_GR
	,MEMBER_NICKNAME
	,MEMBER_BIRTH
	,MEMBER_EMAIL
	,MEMBER_JOINDATE
	,MEMBER_BLACKYN
	,MEMBER_EVENTQTY)
VALUES (
	'testUser00'
	,'testUse0pas'
	,'N'
	,'nickexam00'
	,'19930315'
	,'test@test.co.kr'
	,NOW()
	,'N'
	,0
);

INSERT INTO MEMBERTBL (
	MEMBER_ID
	,MEMBER_PW
	,MEMBER_GR
	,MEMBER_NICKNAME
	,MEMBER_BIRTH
	,MEMBER_EMAIL
	,MEMBER_JOINDATE
	,MEMBER_BLACKYN
	,MEMBER_EVENTQTY)
VALUES (
	'testUser01'
	,'testUse1pas'
	,'N'
	,'nickexam01'
	,'19831215'
	,'test1@test.co.kr'
	,NOW()
	,'N'
	,0
);

INSERT INTO MEMBERTBL (
	MEMBER_ID
	,MEMBER_PW
	,MEMBER_GR
	,MEMBER_NICKNAME
	,MEMBER_BIRTH
	,MEMBER_EMAIL
	,MEMBER_JOINDATE
	,MEMBER_BLACKYN
	,MEMBER_EVENTQTY)
VALUES (
	'testUser02'
	,'testUse1i23'
	,'N'
	,'nickexam02'
	,'19900125'
	,'test2@test.co.kr'
	,NOW()
	,'N'
	,0
);

INSERT INTO MEMBERTBL (
	MEMBER_ID
	,MEMBER_PW
	,MEMBER_GR
	,MEMBER_NICKNAME
	,MEMBER_BIRTH
	,MEMBER_EMAIL
	,MEMBER_JOINDATE
	,MEMBER_BLACKYN
	,MEMBER_EVENTQTY)
VALUES (
	'testUser03'
	,'testUse3ws'
	,'N'
	,'nickexam03'
	,'20001015'
	,'test3@test.co.kr'
	,NOW()
	,'N'
	,0
);

-- ---------------------------------------------------------------------------------------------------

-- 메뉴 추가

INSERT INTO MENUTBL(
CAFE_MENU
,CAFE_MENU_DAE
,CAFE_MENU_NUM
,CAFE_PRICE
)
VALUES (
'아메리카노'
,'커피'
,'00100'
,'5400'
);

COMMIT;

INSERT INTO MENUTBL(
CAFE_MENU
,CAFE_MENU_DAE
,CAFE_MENU_NUM
,CAFE_PRICE
)
VALUES (
'생강차'
,'티'
,'00101'
,'3500'
);

INSERT INTO MENUTBL(
CAFE_MENU
,CAFE_MENU_DAE
,CAFE_MENU_NUM
,CAFE_PRICE
)
VALUES (
'핫 초코'
,'음료'
,'00102'
,'4700'
);


INSERT INTO MENUTBL(
CAFE_MENU
,CAFE_MENU_DAE
,CAFE_MENU_NUM
,CAFE_PRICE
)
VALUES (
'카페 라떼'
,'커피'
,'00103'
,'4500'
);

-- ---------------------------------------------------------------------------------------------------

생강차	티	101	3500
아메리카노	커피	100	5400
핫 초코	음료	102	4700
카페 라떼	커피	103	4500

-- ---------------------------------------------------------------------------------------------------


-- 주문하기

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '100')
,'10'
,NOW()
);

DESC ORDERTBL ;

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '100')
,'5'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser01')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '101')
,'40'
,NOW()
);


INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser01')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '102')
,'14'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser02')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '103')
,'10'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser03')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '103')
,'12'
,NOW()
);


testUser00	아메리카노	10	2023-02-04 08:37:33
testUser00	아메리카노	5	2023-02-04 08:37:53
testUser01	생강차	40	2023-02-04 08:38:04
testUser01	핫 초코	14	2023-02-04 08:38:07
testUser02	카페 라떼	10	2023-02-04 08:38:15
testUser02	카페 라떼	10	2023-02-04 08:38:19
testUser03	카페 라떼	12	2023-02-04 08:38:35

-- 유저 별 주문 조회
-- testUser00
-- 유저별 메뉴, 갯수, 가격 
SELECT M.CAFE_MENU, O.MEMBER_ORDER_COUNT , M.CAFE_PRICE, (O.MEMBER_ORDER_COUNT * M.CAFE_PRICE) AS PAY
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser00'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

아메리카노	10	5400	54000
아메리카노	5	5400	27000

-- 유저별 메뉴, 갯수, 가격 
SELECT M.CAFE_MENU, O.MEMBER_ORDER_COUNT , M.CAFE_PRICE, (O.MEMBER_ORDER_COUNT * M.CAFE_PRICE) AS PAY
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser01'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

생강차	40	3500	140000
핫 초코	14	4700	65800


SELECT M.CAFE_MENU, O.MEMBER_ORDER_COUNT , M.CAFE_PRICE, (O.MEMBER_ORDER_COUNT * M.CAFE_PRICE) AS PAY
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser02'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

카페 라떼	10	4500	45000
카페 라떼	10	4500	45000

-- 유저별 메뉴, 갯수, 가격 
SELECT M.CAFE_MENU, O.MEMBER_ORDER_COUNT , M.CAFE_PRICE, (O.MEMBER_ORDER_COUNT * M.CAFE_PRICE) AS PAY
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser03'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

카페 라떼	12	4500	54000


-- 번호표 뽑기
SELECT MEMBER_ORDERNUM FROM SONNIM WHERE MEMBER_ID = 'testUser00';

-- 결제할 금액 보기
SELECT MEMBER_ORDER_PAY FROM SONNIM WHERE MEMBER_ORDERNUM = (SELECT MEMBER_ORDERNUM ​
FROM SONNIM WHERE MEMBER_ID = 'testUser00');

81000
-- ---------------------------------------------------------------------------------------------------

-- 주문하기 (결제 )
--  손님 별 추가
INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY)
SELECT DISTINCT O.MEMBER_ID,  SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser00'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY)
SELECT DISTINCT O.MEMBER_ID,  SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser01'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY)
SELECT DISTINCT O.MEMBER_ID,  SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser02'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY )
SELECT DISTINCT O.MEMBER_ID,  SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser03'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

SELECT * FROM SONNIM ;

2	testUser00	15	81000
3	testUser01	54	205800
4	testUser02	20	90000
5	testUser03	12	54000

-- ---------------------------------------------------------------------------------------------------


-- 매장 리스트에 넣기
INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '100'
AND   M.CAFE_MENU  = '아메리카노'
AND   O.MEMBER_MENU_NUM = '아메리카노';

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '101'
AND   M.CAFE_MENU  = '생강차'
AND   O.MEMBER_MENU_NUM = '생강차';

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '102'
AND   M.CAFE_MENU  = '핫 초코'
AND   O.MEMBER_MENU_NUM ='핫 초코';

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '103'
AND   M.CAFE_MENU  = '카페 라떼'
AND   O.MEMBER_MENU_NUM ='카페 라떼';


1	아메리카노	15	81000	2023-02-04 08:44:42
2	생강차	40	140000	2023-02-04 08:44:45
3	핫 초코	14	65800	2023-02-04 08:44:46
4	카페 라떼	32	144000	2023-02-04 08:44:49  (위에서 카페라떼 동일 쿼리 두 번 날림)


-- 하루 총 매출 
SELECT SUM(ORDER_PAY) FROM SUBMIT_ORDER WHERE ORDER_DATE LIKE '%2023-02-04%';

430800


-- 매장 리스트에 넣고나면 반드시 아래에 두 테이블에서 해당 아이디에 대한 열 삭제를 해야함.
DELETE FROM SONNIM WHERE MEMBER_ID = 'testUser03';
DELETE FROM ORDERTBL WHERE MEMBER_ID = 'testUser03';


-- ---------------------------------------------------------------------------------------------------
SELECT * FROM SUBMIT_ORDER SO ;



-- 다시 추가해보면 SUBMIT_ORDER 테이블에서 중복이 되지 않고 정렬이 잘 되는 것을 확인할 수 있고 번호표도 중복 안됨.

1	아메리카노	15	81000	2023-02-04 08:44:42
2	생강차	40	140000	2023-02-04 08:44:45
3	핫 초코	14	65800	2023-02-04 08:44:46
4	카페 라떼	32	144000	2023-02-04 08:44:49
5	아메리카노	15	81000	2023-02-04 08:55:09
6	생강차	40	140000	2023-02-04 08:55:23
7	핫 초코	14	65800	2023-02-04 08:56:12
8	카페 라떼	22	99000	2023-02-04 08:56:16
9	아메리카노	15	81000	2023-02-04 09:05:35
10	생강차	40	140000	2023-02-04 09:05:39
11	핫 초코	14	65800	2023-02-04 09:05:43
12	카페 라떼	22	99000	2023-02-04 09:05:45

-- 다시 해보기


-- 주문하기

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '100')
,'10'
,NOW()
);

DESC ORDERTBL ;

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '100')
,'5'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser01')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '101')
,'40'
,NOW()
);


INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser01')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '102')
,'14'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser02')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '103')
,'10'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser03')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '103')
,'12'
,NOW()
);

SELECT * FROM ORDERTBL O ;


SELECT M.CAFE_MENU, O.MEMBER_ORDER_COUNT , M.CAFE_PRICE, (O.MEMBER_ORDER_COUNT * M.CAFE_PRICE) AS PAY
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser00'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;


INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY)
SELECT DISTINCT O.MEMBER_ID,  SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser00'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY)
SELECT DISTINCT O.MEMBER_ID,  SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser01'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY)
SELECT DISTINCT O.MEMBER_ID,  SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser02'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

INSERT INTO SONNIM (MEMBER_ID, MEMBER_ORDER_COUNT, MEMBER_ORDER_PAY )
SELECT DISTINCT O.MEMBER_ID,  SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE)
FROM MENUTBL M, ORDERTBL O 
WHERE O.MEMBER_ID = 'testUser03'
AND   M.CAFE_MENU = O.MEMBER_MENU_NUM;

SELECT * FROM SONNIM S ;


INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '100'
AND   M.CAFE_MENU  = '아메리카노'
AND   O.MEMBER_MENU_NUM = '아메리카노';

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '101'
AND   M.CAFE_MENU  = '생강차'
AND   O.MEMBER_MENU_NUM = '생강차';

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '102'
AND   M.CAFE_MENU  = '핫 초코'
AND   O.MEMBER_MENU_NUM ='핫 초코';

INSERT INTO SUBMIT_ORDER (MENU, ORDER_COUNT, ORDER_PAY, ORDER_DATE)
SELECT DISTINCT M.CAFE_MENU, SUM(MEMBER_ORDER_COUNT), SUM(O.MEMBER_ORDER_COUNT * M.CAFE_PRICE), NOW()
FROM  MENUTBL M, ORDERTBL O 
WHERE M.CAFE_MENU_NUM  = '103'
AND   M.CAFE_MENU  = '카페 라떼'
AND   O.MEMBER_MENU_NUM ='카페 라떼';

SELECT * FROM SONNIM S ;
DELETE FROM SONNIM WHERE MEMBER_ID = 'testUser03';
DELETE FROM ORDERTBL WHERE MEMBER_ID = 'testUser03';

SELECT * FROM ORDERTBL O ;
