-- ORDERTBL


CREATE TABLE ORDERTBL (
   MEMBER_ID            VARCHAR(30)      NOT NULL        COMMENT '회원 아이디'
   ,MEMBER_MENU_NUM     VARCHAR(30)      NOT NULL         COMMENT '메뉴 넘버'
   ,MEMBER_ORDER_COUNT      INT            NOT NULL         COMMENT '음료 주문 수'
   ,MEMBER_ORDER_DATE      DATETIME      NOT NULL         COMMENT '주문한 날짜'
) DEFAULT CHARSET=utf8mb4;

-- 

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '101')
,'10'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '100')
,'5'
,NOW()
);


INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser00')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '102')
,'14'
,NOW()
);

-- ----------------------


INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser01')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '101')
,'40'
,NOW()
);


INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser01')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '102')
,'14'
,NOW()
);

-- -----------------------


INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser02')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '101')
,'8'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser02')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '101')
,'12'
,NOW()
);


INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser02')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '102')
,'5'
,NOW()
);

-- ------------------------------------------

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser03')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '101')
,'10'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser03')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '100')
,'10'
,NOW()
);

INSERT INTO ORDERTBL(
MEMBER_ID
,MEMBER_MENU_NUM
,MEMBER_ORDER_COUNT
,MEMBER_ORDER_DATE
)
VALUES (
(SELECT MEMBER_ID FROM MEMBERTBL WHERE MEMBER_ID = 'testUser03')
,(SELECT CAFE_MENU FROM MENUTBL WHERE CAFE_MENU_NUM = '102')
,'12'
,NOW()
);



SELECT * FROM ordertbl;